# Generated by Django 4.2.3 on 2023-07-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productdetail_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetail',
            options={},
        ),
        migrations.AddField(
            model_name='productdetail',
            name='image_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
