# Generated by Django 4.2.3 on 2023-07-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productdetail_options_productdetail_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
